version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./the_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=hvl
      - POSTGRES_USER=hvl
      - POSTGRES_DB=hvldb